-- =========================================
-- Tabla: USERS
-- =========================================
CREATE TABLE users (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,
    name            VARCHAR2(150)        NOT NULL,
    email           VARCHAR2(150)        NOT NULL UNIQUE,
    password_hash   VARCHAR2(255)        NOT NULL,
    phone           VARCHAR2(30),
    role_id         NUMBER,                          -- FK a ROLES (se agrega en 99_relations.sql)
    is_active       NUMBER(1) DEFAULT 1 NOT NULL,    -- 1 = activo, 0 = bloqueado
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP
);

CREATE INDEX idx_users_email ON users(email);
-- Tabla de usuarios
