-- =========================================
-- Tabla: PRODUCTS
-- =========================================
CREATE TABLE products (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,
    sku             VARCHAR2(50)   NOT NULL UNIQUE,
    name            VARCHAR2(200)  NOT NULL,
    description     CLOB,
    price           NUMBER(10,2)   NOT NULL,
    category_id     NUMBER,                    -- FK a categories.id
    stock           NUMBER         DEFAULT 0 NOT NULL,
    is_published    NUMBER(1)      DEFAULT 1 NOT NULL,
    main_image_url  VARCHAR2(500),
    created_at      TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP
);

CREATE INDEX idx_products_category ON products(category_id);
CREATE INDEX idx_products_name ON products(name);
-- Tabla de productos
