-- =========================================
-- Tabla: CATEGORIES
-- =========================================
CREATE TABLE categories (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY
                PRIMARY KEY,
    name        VARCHAR2(150)  NOT NULL,
    slug        VARCHAR2(150)  NOT NULL UNIQUE,
    parent_id   NUMBER,                -- FK a categories.id (categorías padre)
    is_active   NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE INDEX idx_categories_parent ON categories(parent_id);
-- Tabla de categor�as
