-- =========================================
-- Tabla: ORDERS
-- =========================================
CREATE TABLE orders (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY
                        PRIMARY KEY,
    user_id             NUMBER,                  -- FK a users.id (puede ser NULL si es invitado)
    status              VARCHAR2(30) NOT NULL,   -- 'recibido','pagado','enviado','entregado','cancelado'
    total_amount        NUMBER(10,2) NOT NULL,
    subtotal_amount     NUMBER(10,2),
    tax_amount          NUMBER(10,2),
    discount_amount     NUMBER(10,2),
    payment_status      VARCHAR2(30),            -- 'pendiente','aprobado','rechazado'
    payment_reference   VARCHAR2(100),
    shipping_name       VARCHAR2(150),
    shipping_phone      VARCHAR2(30),
    shipping_address    VARCHAR2(300),
    shipping_city       VARCHAR2(100),
    shipping_state      VARCHAR2(100),
    shipping_postalcode VARCHAR2(20),
    shipping_country    VARCHAR2(100),
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP
);

CREATE INDEX idx_orders_user ON orders(user_id);
CREATE INDEX idx_orders_status ON orders(status);
-- Tabla de pedidos
