-- =========================================
-- Tabla: ORDER_ITEMS
-- =========================================
CREATE TABLE order_items (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,
    order_id        NUMBER NOT NULL,         -- FK a orders.id
    product_id      NUMBER NOT NULL,         -- FK a products.id
    quantity        NUMBER      NOT NULL,
    unit_price      NUMBER(10,2) NOT NULL,   -- precio al momento de la compra
    discount_amount NUMBER(10,2),
    subtotal        NUMBER(10,2) NOT NULL
);

CREATE INDEX idx_order_items_order ON order_items(order_id);
CREATE INDEX idx_order_items_product ON order_items(product_id);
-- Items del pedido
