-- =========================================
-- Tabla: INVENTORY_MOVEMENTS
-- =========================================
CREATE TABLE inventory_movements (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,
    product_id      NUMBER      NOT NULL,          -- FK a products.id
    change_qty      NUMBER      NOT NULL,          -- positivo = entrada, negativo = salida
    reason          VARCHAR2(50) NOT NULL,         -- 'ajuste','venta','devolucion'
    source_type     VARCHAR2(50),                  -- 'order','manual'
    source_id       NUMBER,                        -- id del pedido u origen
    created_by      NUMBER,                        -- FK a users.id (quién hizo el cambio)
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_inventory_product ON inventory_movements(product_id);
-- Inventario
