-- =========================================
-- Tabla: WISHLIST_ITEMS
-- =========================================
CREATE TABLE wishlist_items (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY
                PRIMARY KEY,
    user_id     NUMBER      NOT NULL,      -- FK users.id
    product_id  NUMBER      NOT NULL,      -- FK products.id
    created_at  TIMESTAMP   DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uq_wishlist_user_product
    ON wishlist_items(user_id, product_id);

CREATE INDEX idx_wishlist_user ON wishlist_items(user_id);
