-- =========================================
-- Tabla: COUPONS
-- =========================================
CREATE TABLE coupons (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,
    code            VARCHAR2(50)   NOT NULL UNIQUE,
    description     VARCHAR2(255),
    discount_type   VARCHAR2(20)   NOT NULL,      -- 'percent' o 'amount'
    discount_value  NUMBER(10,2)   NOT NULL,
    min_amount      NUMBER(10,2),
    max_redemptions NUMBER,
    valid_from      DATE,
    valid_to        DATE,
    is_active       NUMBER(1)      DEFAULT 1 NOT NULL,
    created_at      TIMESTAMP      DEFAULT CURRENT_TIMESTAMP
);

-- =========================================
-- Tabla: COUPON_REDEMPTIONS
-- =========================================
CREATE TABLE coupon_redeptions (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY
                PRIMARY KEY,
    coupon_id   NUMBER      NOT NULL,      -- FK coupons.id
    order_id    NUMBER      NOT NULL,      -- FK orders.id
    user_id     NUMBER,                    -- FK users.id (puede ser null si invitado)
    redeemed_at TIMESTAMP   DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_redemptions_coupon ON coupon_redeptions(coupon_id);
CREATE INDEX idx_redemptions_order  ON coupon_redeptions(order_id);
