-- =========================================
-- Tabla: CMS_PAGES
-- =========================================
CREATE TABLE cms_pages (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY
                PRIMARY KEY,
    slug        VARCHAR2(150)  NOT NULL UNIQUE,
    title       VARCHAR2(200)  NOT NULL,
    content     CLOB           NOT NULL,
    is_published NUMBER(1)     DEFAULT 0 NOT NULL,
    created_by  NUMBER,                    -- FK users.id (operador/admin)
    updated_by  NUMBER,                    -- FK users.id
    created_at  TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP
);

CREATE INDEX idx_cms_published ON cms_pages(is_published);
