-- =========================================
-- Tabla: RMA_REQUESTS
-- =========================================
CREATE TABLE rma_requests (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,
    order_id        NUMBER      NOT NULL,          -- FK orders.id
    user_id         NUMBER      NOT NULL,          -- FK users.id
    reason          VARCHAR2(255) NOT NULL,
    status          VARCHAR2(30)  DEFAULT 'pendiente', -- 'pendiente','aprobada','rechazada'
    type            VARCHAR2(20)  NOT NULL,        -- 'devolucion','cancelacion'
    created_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    reviewed_by     NUMBER,                        -- FK users.id (admin)
    reviewed_at     TIMESTAMP
);

CREATE INDEX idx_rma_order ON rma_requests(order_id);
CREATE INDEX idx_rma_user  ON rma_requests(user_id);
