-- =========================================
-- Tabla: CONTACT_MESSAGES
-- =========================================
CREATE TABLE contact_messages (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,
    name            VARCHAR2(150)  NOT NULL,
    email           VARCHAR2(150)  NOT NULL,
    subject         VARCHAR2(200),
    message         CLOB           NOT NULL,
    status          VARCHAR2(30)   DEFAULT 'nuevo',  -- 'nuevo','leido','respondido'
    created_at      TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP
);

CREATE INDEX idx_contact_status ON contact_messages(status);
