-- =========================================
-- Tabla: NOTIFICATION_PREFERENCES
-- =========================================
CREATE TABLE notification_preferences (
    id                      NUMBER GENERATED BY DEFAULT AS IDENTITY
                            PRIMARY KEY,
    user_id                 NUMBER      NOT NULL,          -- FK users.id
    marketing_emails        NUMBER(1)   DEFAULT 1 NOT NULL,
    operational_emails      NUMBER(1)   DEFAULT 1 NOT NULL,
    whatsapp_notifications  NUMBER(1)   DEFAULT 0 NOT NULL,
    data_download_requested NUMBER(1)   DEFAULT 0 NOT NULL,
    data_delete_requested   NUMBER(1)   DEFAULT 0 NOT NULL,
    updated_at              TIMESTAMP   DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uq_notification_user ON notification_preferences(user_id);
