-- =========================================
-- Tabla: SHIPPING_METHODS
-- =========================================
CREATE TABLE shipping_methods (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY
                PRIMARY KEY,
    name        VARCHAR2(150)  NOT NULL,
    code        VARCHAR2(50)   NOT NULL UNIQUE,   -- 'estandar','express'
    base_cost   NUMBER(10,2)   NOT NULL,
    is_active   NUMBER(1)      DEFAULT 1 NOT NULL,
    created_at  TIMESTAMP      DEFAULT CURRENT_TIMESTAMP
);

-- =========================================
-- Tabla: ORDER_SHIPMENTS
-- =========================================
CREATE TABLE order_shipments (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,
    order_id        NUMBER      NOT NULL,      -- FK orders.id
    shipping_method_id NUMBER   NOT NULL,      -- FK shipping_methods.id
    tracking_number VARCHAR2(100),
    carrier         VARCHAR2(100),
    status          VARCHAR2(30) DEFAULT 'pendiente',  -- 'pendiente','en_transito','entregado'
    shipped_at      TIMESTAMP,
    delivered_at    TIMESTAMP,
    created_at      TIMESTAMP   DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_shipments_order ON order_shipments(order_id);
