-- =========================================
-- Tabla: CHATBOT_SESSIONS
-- =========================================
CREATE TABLE chatbot_sessions (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,
    user_id         NUMBER,                -- FK users.id (puede ser null si visitante)
    session_token   VARCHAR2(100) NOT NULL UNIQUE,
    started_at      TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    ended_at        TIMESTAMP
);

-- =========================================
-- Tabla: CHATBOT_MESSAGES
-- =========================================
CREATE TABLE chatbot_messages (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,
    session_id      NUMBER      NOT NULL,      -- FK chatbot_sessions.id
    sender          VARCHAR2(20) NOT NULL,     -- 'user' o 'bot'
    message         CLOB         NOT NULL,
    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    intent          VARCHAR2(100),
    confidence      NUMBER(5,2)
);

CREATE INDEX idx_chatbot_messages_session ON chatbot_messages(session_id);
