-- =========================================
-- Tabla: AUDIT_LOGS
-- =========================================
CREATE TABLE audit_logs (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY
                PRIMARY KEY,
    user_id     NUMBER,
    action      VARCHAR2(100) NOT NULL,       -- 'login','update_product','change_status_order', etc.
    entity      VARCHAR2(100),
    entity_id   NUMBER,
    ip_address  VARCHAR2(45),
    user_agent  VARCHAR2(255),
    created_at  TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    details     CLOB
);

CREATE INDEX idx_audit_user   ON audit_logs(user_id);
CREATE INDEX idx_audit_entity ON audit_logs(entity, entity_id);
